[package]
name = "nn"
version = "0.1.0"
edition = "2024"

[dependencies]

[[example]]
name = "linear-regression"
path = "./examples/linear_regression.rs"

[[example]]
name = "quadratic-regression"
path = "./examples/quadratic_regression.rs"
